### ISSUE TITLE
Error compiling cvstats.cpp after "make -j$nproc"

### ISSUE THREAD

**Issue by kalum93** [haldai/LogicalVision2#4]
Hi thanks a lot for u're work. I need an help! After installing your requirements, I ran this command "make -j$nproc". These files cvcluster.so, cvknn.so,  cvio.so, cvdraw.so and cvsampler.so are compiled without errors, but for cvstats.cpp I get this error:
"In file included from cvstats.cpp:17:0:
statistics.hpp: In function ‘PlTerm pl_train_adaboost(const mat&, const arma::Row<long unsigned int>&, size_t, size_t, size_t, double)’:
statistics.hpp:280:67: error: no matching function for call to ‘mlpack::adaboost::AdaBoost<mlpack::decision_stump::DecisionStump<> >::AdaBoost(const mat&, const arma::subview_row<long unsigned int>, const size_t&, mlpack::decision_stump::DecisionStump<>&, const size_t&, const double&)’
                                          ds, iterations, tolerance);
                                                                   ^
In file included from /usr/include/mlpack/methods/adaboost/adaboost.hpp:183:0,
                 from statistics.hpp:29,
                 from cvstats.cpp:17:
/usr/include/mlpack/methods/adaboost/adaboost_impl.hpp:56:1: note: candidate: mlpack::adaboost::AdaBoost<WeakLearnerType, MatType>::AdaBoost(double) [with WeakLearnerType = mlpack::decision_stump::DecisionStump<>; MatType = arma::Mat<double>]
 AdaBoost<WeakLearnerType, MatType>::AdaBoost(const double tolerance) :
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/mlpack/methods/adaboost/adaboost_impl.hpp:56:1: note:   candidate expects 1 argument, 6 provided
/usr/include/mlpack/methods/adaboost/adaboost_impl.hpp:44:1: note: candidate: mlpack::adaboost::AdaBoost<WeakLearnerType, MatType>::AdaBoost(const MatType&, const arma::Row<long unsigned int>&, const WeakLearnerType&, size_t, double) [with WeakLearnerType = mlpack::decision_stump::DecisionStump<>; MatType = arma::Mat<double>; size_t = long unsigned int]
 AdaBoost<WeakLearnerType, MatType>::AdaBoost(
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/mlpack/methods/adaboost/adaboost_impl.hpp:44:1: note:   candidate expects 5 arguments, 6 provided
In file included from statistics.hpp:29:0,
                 from cvstats.cpp:17:
/usr/include/mlpack/methods/adaboost/adaboost.hpp:81:7: note: candidate: mlpack::adaboost::AdaBoost<mlpack::decision_stump::DecisionStump<> >::AdaBoost(const mlpack::adaboost::AdaBoost<mlpack::decision_stump::DecisionStump<> >&)
 class AdaBoost
       ^~~~~~~~
/usr/include/mlpack/methods/adaboost/adaboost.hpp:81:7: note:   candidate expects 1 argument, 6 provided
/usr/include/mlpack/methods/adaboost/adaboost.hpp:81:7: note: candidate: mlpack::adaboost::AdaBoost<mlpack::decision_stump::DecisionStump<> >::AdaBoost(mlpack::adaboost::AdaBoost<mlpack::decision_stump::DecisionStump<> >&&)
/usr/include/mlpack/methods/adaboost/adaboost.hpp:81:7: note:   candidate expects 1 argument, 6 provided
In file included from cvstats.cpp:17:0:
statistics.hpp: In function ‘PlTerm pl_train_adaboost_perceptron(const mat&, const arma::Row<long unsigned int>&, size_t, size_t, size_t, double)’:
statistics.hpp:303:72: error: no matching function for call to ‘mlpack::adaboost::AdaBoost<mlpack::perceptron::Perceptron<> >::AdaBoost(const mat&, const arma::subview_row<long unsigned int>, const size_t&, mlpack::perceptron::Perceptron<>&, const size_t&, const double&)’
                                                p, iterations, tolerance);
                                                                        ^
In file included from /usr/include/mlpack/methods/adaboost/adaboost.hpp:183:0,
                 from statistics.hpp:29,
                 from cvstats.cpp:17:
/usr/include/mlpack/methods/adaboost/adaboost_impl.hpp:56:1: note: candidate: mlpack::adaboost::AdaBoost<WeakLearnerType, MatType>::AdaBoost(double) [with WeakLearnerType = mlpack::perceptron::Perceptron<>; MatType = arma::Mat<double>]
 AdaBoost<WeakLearnerType, MatType>::AdaBoost(const double tolerance) :
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/mlpack/methods/adaboost/adaboost_impl.hpp:56:1: note:   candidate expects 1 argument, 6 provided
/usr/include/mlpack/methods/adaboost/adaboost_impl.hpp:44:1: note: candidate: mlpack::adaboost::AdaBoost<WeakLearnerType, MatType>::AdaBoost(const MatType&, const arma::Row<long unsigned int>&, const WeakLearnerType&, size_t, double) [with WeakLearnerType = mlpack::perceptron::Perceptron<>; MatType = arma::Mat<double>; size_t = long unsigned int]
 AdaBoost<WeakLearnerType, MatType>::AdaBoost(
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/mlpack/methods/adaboost/adaboost_impl.hpp:44:1: note:   candidate expects 5 arguments, 6 provided
In file included from statistics.hpp:29:0,
                 from cvstats.cpp:17:
/usr/include/mlpack/methods/adaboost/adaboost.hpp:81:7: note: candidate: mlpack::adaboost::AdaBoost<mlpack::perceptron::Perceptron<> >::AdaBoost(const mlpack::adaboost::AdaBoost<mlpack::perceptron::Perceptron<> >&)
 class AdaBoost
       ^~~~~~~~
/usr/include/mlpack/methods/adaboost/adaboost.hpp:81:7: note:   candidate expects 1 argument, 6 provided
/usr/include/mlpack/methods/adaboost/adaboost.hpp:81:7: note: candidate: mlpack::adaboost::AdaBoost<mlpack::perceptron::Perceptron<> >::AdaBoost(mlpack::adaboost::AdaBoost<mlpack::perceptron::Perceptron<> >&&)
/usr/include/mlpack/methods/adaboost/adaboost.hpp:81:7: note:   candidate expects 1 argument, 6 provided
Makefile:75: recipe for target 'cvstats.o' failed
make[1]: *** [cvstats.o] Error 1
make[1]: uscita dalla directory "/home/caan-ubuntu/LogicalVision2/src/cpp"
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
"
is there a lib which I forgot to install?
Have a good day!

**Comment by haldai** [comment]
Hi, thanks for your feedback!

I have fixed the README file, you should also compile and install [`mlpack`](https://github.com/mlpack/mlpack) for compiling the statistical classifiers.

The support of opencv 4 is added, too.

**Comment by kalum93** [comment]
> Hi, thanks for your feedback!
> 
> I have fixed the README file, you should also compile and install [`mlpack`](https://github.com/mlpack/mlpack) for compiling the statistical classifiers.
> 
> The support of opencv 4 is added, too.

That's great! best regards ;)
